[theme]
base = "light"
primaryColor = "#4F8A8B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
runOnSave = true

[client]
showSidebarNavigation = true